import { initializeTestEnvironment, assertSucceeds, assertFails } from "@firebase/rules-unit-testing";
import { readFileSync } from "fs";
import { doc, getDoc, setDoc, updateDoc, deleteDoc, collection, collectionGroup, getDocs, addDoc } from "firebase/firestore";

const env = await initializeTestEnvironment({ projectId: "demo-gates", firestore: { rules: readFileSync(new URL("../firestore.rules", import.meta.url),"utf8"), host:"127.0.0.1", port:8089 } });
const admin = env.authenticatedContext("adminUid", { email:"bm.blancom@gmail.com", email_verified:true }).firestore();
const admin2 = env.authenticatedContext("admin2", { email:"barbarabmontero@gmail.com", email_verified:true }).firestore();
const fakeAdmin = env.authenticatedContext("fake", { email:"bm.blancom@gmail.com", email_verified:false }).firestore();
const A = env.authenticatedContext("uidA", { email:"a@x.com", email_verified:true }).firestore();
const B = env.authenticatedContext("uidB", { email:"b@x.com", email_verified:true }).firestore();
const anon = env.unauthenticatedContext().firestore();
let n=0; const t = async (name, p) => { await p; n++; console.log("ok -", name); };

await t("anon no crea recorrido", assertFails(setDoc(doc(anon,"recorridos/r1"), {nombre:"x"})));
await t("admin email no verificado no crea", assertFails(setDoc(doc(fakeAdmin,"recorridos/r1"), {nombre:"x"})));
await t("admin crea recorrido", assertSucceeds(setDoc(doc(admin,"recorridos/r1"), {nombre:"Oct", dias:3, activo:true})));
await t("admin2 edita recorrido", assertSucceeds(updateDoc(doc(admin2,"recorridos/r1"), {dias:4})));
await t("admin crea lauti", assertSucceeds(setDoc(doc(admin,"recorridos/r1/participantes/lauti"), {nombre:"Lauti", uid:null})));
await t("admin crea juan (sin campo uid)", assertSucceeds(setDoc(doc(admin,"recorridos/r1/participantes/juan"), {nombre:"Juan"})));
await t("usuario no crea participante", assertFails(setDoc(doc(A,"recorridos/r1/participantes/intruso"), {nombre:"X", uid:"uidA"})));
await t("anon lee recorrido", assertSucceeds(getDoc(doc(anon,"recorridos/r1"))));
await t("A vincula lauti", assertSucceeds(updateDoc(doc(A,"recorridos/r1/participantes/lauti"), {uid:"uidA", reclamado:1})));
await t("B no puede robar lauti", assertFails(updateDoc(doc(B,"recorridos/r1/participantes/lauti"), {uid:"uidB", reclamado:2})));
await t("B no vincula juan a nombre de A", assertFails(updateDoc(doc(B,"recorridos/r1/participantes/juan"), {uid:"uidA"})));
await t("B vincula juan", assertSucceeds(updateDoc(doc(B,"recorridos/r1/participantes/juan"), {uid:"uidB", reclamado:2})));
await t("B no cambia su nombre", assertFails(updateDoc(doc(B,"recorridos/r1/participantes/juan"), {nombre:"Juancito"})));
await t("B guarda su notif", assertSucceeds(updateDoc(doc(B,"recorridos/r1/participantes/juan"), {notif:{manana:{on:true,hora:"09:00"}}, actualizado:1})));
await t("B guarda su cierre", assertSucceeds(updateDoc(doc(B,"recorridos/r1/participantes/juan"), {cierre:{pct:80, dia:2, fecha:1}, vioCierre:true})));
await t("B no toca el cierre de A", assertFails(updateDoc(doc(B,"recorridos/r1/participantes/lauti"), {cierre:{pct:0}})));
await t("B no toca notif de A", assertFails(updateDoc(doc(B,"recorridos/r1/participantes/lauti"), {notif:{}})));
const tarea = {dia:1, key:"milo_seco_1", pid:"lauti", nombre:"Lauti", uid:"uidA", creado:1};
await t("A tilda tarea", assertSucceeds(setDoc(doc(A,"recorridos/r1/tareas/1_milo_seco_1"), tarea)));
await t("B no re-tilda tarea de A", assertFails(setDoc(doc(B,"recorridos/r1/tareas/1_milo_seco_1"), {...tarea, pid:"juan", uid:"uidB"})));
await t("B no destilda tarea de A", assertFails(deleteDoc(doc(B,"recorridos/r1/tareas/1_milo_seco_1"))));
await t("B no tilda a nombre de A", assertFails(setDoc(doc(B,"recorridos/r1/tareas/1_zoe_seco_1"), {...tarea, key:"zoe_seco_1", uid:"uidB"})));
await t("B no usa id inconsistente", assertFails(setDoc(doc(B,"recorridos/r1/tareas/2_zoe_seco_1"), {dia:1, key:"zoe_seco_1", pid:"juan", uid:"uidB"})));
const base = {nombre:"Juan", pid:"juan", uid:"uidB", creado:3};
await t("tarea inventada rechazada", assertFails(setDoc(doc(B,"recorridos/r1/tareas/1_hack"), {...base, dia:1, key:"hack"})));
await t("día fuera del recorrido rechazado", assertFails(setDoc(doc(B,"recorridos/r1/tareas/99_zoe_seco_2"), {...base, dia:99, key:"zoe_seco_2"})));
await t("día 0 rechazado", assertFails(setDoc(doc(B,"recorridos/r1/tareas/0_zoe_seco_2"), {...base, dia:0, key:"zoe_seco_2"})));
await t("día como texto rechazado", assertFails(setDoc(doc(B,"recorridos/r1/tareas/1_zoe_seco_2"), {...base, dia:"1", key:"zoe_seco_2"})));
await t("campo extra (puntos) rechazado", assertFails(setDoc(doc(B,"recorridos/r1/tareas/1_zoe_seco_2"), {...base, dia:1, key:"zoe_seco_2", puntos:1000})));
await t("B tilda la suya", assertSucceeds(setDoc(doc(B,"recorridos/r1/tareas/1_zoe_seco_1"), {dia:1, key:"zoe_seco_1", pid:"juan", nombre:"Juan", uid:"uidB", creado:2})));
await t("A destilda la suya", assertSucceeds(deleteDoc(doc(A,"recorridos/r1/tareas/1_milo_seco_1"))));
await t("tarea migrada (uid null) la destilda su dueño", (async()=>{ await setDoc(doc(admin,"recorridos/r1/tareas/2_milo_seco_1"), {dia:2,key:"milo_seco_1",pid:"lauti",uid:null}); await assertSucceeds(deleteDoc(doc(A,"recorridos/r1/tareas/2_milo_seco_1"))); })());
await t("anon no tilda", assertFails(setDoc(doc(anon,"recorridos/r1/tareas/3_milo_seco_1"), {dia:3,key:"milo_seco_1",pid:"lauti",uid:null})));
await t("anon lee ranking (collectionGroup participantes)", assertSucceeds(getDocs(collectionGroup(anon,"participantes"))));
await t("anon lee ranking (collectionGroup tareas)", assertSucceeds(getDocs(collectionGroup(anon,"tareas"))));
await t("anon no comenta", assertFails(addDoc(collection(anon,"comentarios"), {uid:null, mensaje:"hola"})));
await t("A comenta global", assertSucceeds(setDoc(doc(A,"comentarios/c1"), {uid:"uidA", nombre:"Lauti", mensaje:"hola"})));
await t("comentario vacío rechazado", assertFails(setDoc(doc(A,"comentarios/vacio"), {uid:"uidA", mensaje:""})));
await t("comentario gigante rechazado", assertFails(setDoc(doc(A,"comentarios/largo"), {uid:"uidA", mensaje:"x".repeat(2001)})));
await t("A no comenta como B", assertFails(setDoc(doc(A,"comentarios/c2"), {uid:"uidB", mensaje:"x"})));
await t("B no edita comentario de A", assertFails(updateDoc(doc(B,"comentarios/c1"), {mensaje:"hackeado"})));
await t("B no borra comentario de A", assertFails(deleteDoc(doc(B,"comentarios/c1"))));
await t("A edita su comentario", assertSucceeds(updateDoc(doc(A,"comentarios/c1"), {mensaje:"hola!", editado:1})));
await t("A no transfiere su comentario", assertFails(updateDoc(doc(A,"comentarios/c1"), {uid:"uidB"})));
await t("A comenta en recorrido", assertSucceeds(setDoc(doc(A,"recorridos/r1/comentarios/c1"), {uid:"uidA", mensaje:"hola"})));
await t("A borra su comentario del recorrido", assertSucceeds(deleteDoc(doc(A,"recorridos/r1/comentarios/c1"))));
await t("admin borra comentario ajeno", assertSucceeds(deleteDoc(doc(admin,"comentarios/c1"))));
await t("admin libera cuenta", assertSucceeds(updateDoc(doc(admin,"recorridos/r1/participantes/lauti"), {uid:null})));
await t("comentario viejo sin uid: nadie lo edita", (async()=>{ await env.withSecurityRulesDisabled(c => setDoc(doc(c.firestore(),"comentarios/viejo"), {nombre:"X", mensaje:"m"})); await assertFails(updateDoc(doc(A,"comentarios/viejo"), {mensaje:"y"})); })());
console.log(`\n${n} pruebas OK`);
await env.cleanup();
process.exit(0);
